apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Frontside's Backstage Developer Portal
  annotations:
    github.com/project-slug: thefrontside/playhouse
    humanitec.com/orgId: the-frontside-software-inc
    humanitec.com/appId: backstage
    some-domain.com/website-url: some-value
spec:
  type: website
  owner: engineering@frontside.com
  lifecycle: production
  providesApis:
    - backstage-graphql-api
