{% raw %}
name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
{% endraw %}
      HUMANITEC_ORG: ${{ values.orgId | dump }}
      COMPONENT_NAME: ${{ values.componentName | dump }}
{% raw %}

    steps:
      - uses: actions/checkout@v3

      - name: Google Cloud Service Account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authenticate to Artifacts Registry
        run: gcloud auth configure-docker ${{ secrets.DOCKER_HOST }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: {% endraw %}${{ values.registryUrl }}/${{ values.componentName }}{% raw %}:${{github.sha}}

      - name: Notify Humanitec
        run: |
          curl \
            --request POST "https://api.humanitec.io/orgs/$HUMANITEC_ORG/images/$COMPONENT_NAME/builds" \
            --header "Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data-raw '{ 
                "branch": "'${{github.ref_name}}'",
                "commit": "'${{github.sha}}'",
                "image": "'{% endraw %}${{ values.registryUrl }}/${{ values.componentName }}{% raw %}:${{github.sha}}'",
                "tags": ["'${{github.sha}}'"]
            }'
{% endraw %}
