name: Compile and Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      # Installing yarn globaly so the workflow will work in `act`
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn tsc
      - run: docker-compose up &
      - run: yarn test --detectOpenHandles --runInBand

